- name: Install Caddy via package
  include_tasks: install-package.yml
  when: caddy_install_source != 'package'
  tags:
    - caddy

- name: Install Caddy via binary
  include_tasks: install-binary.yml
  when: caddy_install_source != 'package'
  tags:
    - caddy
