- name: DEBIAN | Add repository
  apt_repository:
    repo: deb [trusted=yes] https://apt.fury.io/caddy/ /
    mode: '0644'
    filename: caddy-fury
  tags:
    - caddy

- name: DEBIAN | Install caddy
  apt:
    name: caddy
    state: latest
  tags:
    - caddy

- name: DEBIAN | Set capabilities
  community.general.capabilities:
    capability: cap_net_bind_service+ep
    path: /usr/bin/caddy
  tags:
    - caddy
  when: ansible_facts.distribution_major_version is version('8', '<=')
