- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - default.yml
      paths:
        - vars
  tags:
    - caddy

- include_tasks: install-{{ ansible_facts.os_family }}.yml
  tags:
    - caddy

- name: Copy main Caddy config
  template:
    src: "{{ caddy_config_file }}.j2"
    dest: "{{ caddy_config_path }}/{{ caddy_config_file }}"
    lstrip_blocks: yes
    owner: root
    group: root
    mode: '0644'
  notify: reload caddy
  tags:
    - caddy
    - caddy_config

- name: Create conf.d directory
  file:
    path: "{{ caddy_config_path }}/conf.d"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - caddy

- name: Start and enable Caddy
  service:
    name: "{{ caddy_service_name }}"
    state: started
    enabled: yes
  register: service_start
  retries: 5
  until: service_start is success
  tags:
    - caddy
    - caddy_service
