Vagrant.configure(2) do |config|
  # config.dns.tld = 'vagrant.dev'

  # CentOS 6
  config.vm.define 'caddy-centos6' do |centos6|
    centos6.vm.box = 'samdoran/centos6'
    centos6.vm.hostname = 'caddy-centos6'
    centos6.vm.network 'private_network', ip: '10.77.19.100'
    config.vm.provider 'virtualbox' do |vbox|
      vbox.name = 'caddy-centos6'
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # CentOS 7
  config.vm.define 'caddy-centos7' do |centos7|
    centos7.vm.box = 'samdoran/centos7'
    centos7.vm.hostname = 'caddy-centos7'
    centos7.vm.network 'private_network', ip: '10.77.19.101'
    config.vm.provider 'virtualbox' do |vbox|
      vbox.name = 'caddy-centos7'
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # Ubuntu 14.04
  config.vm.define 'caddy-ub14' do |ub14|
    ub14.vm.box = 'geerlingguy/ubuntu1404'
    ub14.vm.hostname = 'caddy-ub14'
    ub14.vm.network 'private_network', ip: '10.77.19.103'
    config.vm.provider 'virtualbox' do |vbox|
      vbox.name = 'caddy-ub14'
      vbox.cpus = 1
      vbox.memory = 256
    end
  end

  # Ubuntu 16.04
  config.vm.define 'caddy-ub16' do |ub16|
    ub16.vm.box = 'geerlingguy/ubuntu1604'
    ub16.vm.hostname = 'caddy-ub16'
    ub16.vm.network 'private_network', ip: '10.77.19.104'
    ub16.vm.provider 'virtualbox' do |vbox|
      vbox.name = 'caddy-ub16'
      vbox.cpus = 1
      vbox.memory = 256
    end
  end

  # Ubuntu 18.04
  config.vm.define 'caddy-ub18' do |ub18|
    ub18.vm.box = 'geerlingguy/ubuntu1804'
    ub18.vm.hostname = 'caddy-ub18'
    ub18.vm.network 'private_network', ip: '10.77.19.105'
    ub18.vm.provider 'virtualbox' do |vbox|
      vbox.name = 'caddy-ub18'
      vbox.cpus = 1
      vbox.memory = 256
    end
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'vagrant.yml'
    ansible.compatibility_mode = '2.0'
  end
end
