dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint -x 204,403,502
  yamllint -c molecule/yamllint.yml .
platforms:
  - name: caddy-test-custom
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos7}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  name: custom build
verifier:
  name: ansible
